# Generated by Django 5.2.3 on 2025-06-23 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0003_order_offer_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='offer_type',
        ),
    ]
