from django.urls import path
from .views import UserProfileList, UserProfileDetail, RegistrationView, CustomLogInView, BusinessUserListView, CustomerUserListView

urlpatterns = [
    path('profile/', UserProfileList.as_view(), name='userprofile-list'),
    path('profile/<int:pk>/', UserProfileDetail.as_view(), name= 'userprofile-detail'),
    path('registration/', RegistrationView.as_view(), name='registration'),
    path('login/', CustomLogInView.as_view(), name='login'),
    path('profiles/business/', BusinessUserListView.as_view(), name='business-user-list'),
    path('profiles/customer/', CustomerUserListView.as_view(), name='customer-user-list')

]

# from django.urls import path, include
# from rest_framework.routers import DefaultRouter
# from . import views # Assuming your Viewsets are in a file named views.py in the current app

# # Create a router instance
# router = DefaultRouter()

# # Register your Viewsets with the router.
# # The first argument is the URL prefix (e.g., 'profiles' will result in /profiles/, /profiles/{pk}/ etc.)
# # The second argument is your ViewSet class.
# # The 'basename' argument is used to name the URL patterns. It's especially important
# # for ViewSets that do not have a .queryset attribute (like CustomAuthViewSet)
# # or if you want to provide a custom name for URL reversing.

# router.register(r'profiles', views.UserProfileViewSet, basename='user-profile')
# router.register(r'auth', views.CustomAuthViewSet, basename='auth')
# router.register(r'business', views.BusinessUserViewSet, basename='business-users')
# router.register(r'customer', views.CustomerUserViewSet, basename='customer-users')


# urlpatterns = [
#     # Include the URLs generated by the router.
#     # This single line replaces all the individual paths for your ViewSets.
#     path('', include(router.urls)),

#     # Optional: If you have any other views that are NOT ViewSet-based,
#     # you would add them here.
#     # Example: path('api/some-other-endpoint/', views.SomeOtherAPIView.as_view(), name='some-other-api'),
# ]