# Generated by Django 5.2.3 on 2025-07-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0004_offerdetail_created_at_offerdetail_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='image',
            new_name='file',
        ),
        migrations.AddField(
            model_name='offerdetail',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='offer_pictures/'),
        ),
    ]
