# Generated by Django 5.2.3 on 2025-07-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0005_rename_image_offer_file_offerdetail_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerdetail',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
