# Generated by Django 5.2.3 on 2025-07-07 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0007_alter_offer_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerdetail',
            name='revisions',
            field=models.IntegerField(default=0),
        ),
    ]
