# Generated by Django 5.2.3 on 2025-07-08 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0008_alter_offerdetail_revisions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='file',
        ),
        migrations.RemoveField(
            model_name='offerdetail',
            name='file',
        ),
        migrations.AddField(
            model_name='offer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='offer_images/'),
        ),
        migrations.AddField(
            model_name='offerdetail',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='offer_images/'),
        ),
    ]
